@echo off

if exist *.class (del *.class) else (echo "not exist")
javac AutoGenerateDimens.java
jar cvfe AutoGenerateDimens.jar AutoGenerateDimens AutoGenerateDimens.class
#java AutoGenerateDimens
java -jar AutoGenerateDimens.jar

pause
